blackbeam/rust-mysql-simple

src/io.rs

This change fixes a panic I encountered when receiving large packets from a database; the sequence number overflowed causing an arithmetic exception.

Explicitly wrap incrementing the packet sequence number.

---

src/error.rs

- fix `{:?}` formatting in `fmt::Display`
- fix `{}` formatting in `fmt::Debug`

fix format strings

---

src/lib.rs

There were some small typos in the documentation of the crate.

Fixed some typos

---

Cargo.toml
src/io.rs

I ran into issues when trying to use Hyper and Mysql in the same project as they require different OpenSSL versions.  Since Hyper seems to be using the latest version, this PR pulls mysql up to the same version.

Upgrade to OpenSSL 0.7.4

---

README.md

Fix for cargo notation, same as in the docs, leading to confusing warnings.
Looks like I oversaw this one..

Fix cargo notation in readme

---

Cargo.toml
README.md
src/lib.rs
src/uuid.rs

This commit implements the FromValue trait for the Uuid type.
It is quite convenient to do that because it reduces the boilerplate when writing SQL queries.
It's an optional feature so, no new dependencies are introduced by default.
I understand that UUIDs are not an official SQL type, but since traits can only be implemented in either the crate the trait or the struct was defined in, this feature has to be implemented in either the uuid or the mysql crate. And doing that in the uuid crate would obviously be wrong.

Add support for UUIDs

---

src/conn/mod.rs
src/conn/opts.rs
src/conn/pool.rs

This PR lets you set a custom "local infile handler" for a connection. Subsequent requests from the server for a local file will be redirected to this handler. This allows for very fast insertion of data.

Add support for local infile handlers

---

src/lib.rs

This crate implements own trait for external types. It's better to keep that crates published for convenience.
Reason:
```rust
impl FromValue for NaiveDateTime
impl FromValue for NaiveDate
impl FromValue for NaiveTime
impl FromValue for Timespec
impl FromValue for Duration
impl FromValue for Duration
```

Publish chrono and time crates

---

src/conn/mod.rs
src/conn/pool.rs

This is useful for creating functions that can take any kind of connection or transaction as a parameter.

Add a generic connection trait

---

src/io/mod.rs

Hi.
https://github.com/rust-lang/rust/pull/42125 is going to fix some holes in `rustc`'s privacy checker.
Unfortunately, it can break code sometimes.
`crates.io` testing found 3 unexpected regressions, including this crate.
This PR updates the code to build successfully with https://github.com/rust-lang/rust/pull/42125

Fix build on nightly rustc

---

src/conn/opts.rs
src/conn/pool.rs

This PR implements `From` for `Into<String>` on `Opts`, i.e. one can use either `&str` or `String` (or anything else that implements `Into<String>`) as argument type for `Pool::new`.

Allow to pass &str or String

---

src/conn/mod.rs

It's useful to have a non-panicking way to get column values from a row. Nullable columns seem to fail with the traditional `.{get|take}` methods.

feat: add get_opt and take_opt to row

---

README.md

I added a link to the page describing the JSON type in MySQL in the section "JSON Support" based on the reply to my question in #117.

Add a link to page describing JSON type in MySQL

---

src/conn/mod.rs
src/conn/opts.rs
src/io/mod.rs
src/io/tcp.rs

When a command (or part of a command) is much smaller than the network MTU, a (well-known) problem occurs between delayed ACKs and Nagle's algorithm. Specifically, Nagle tries to maximize packet size, and will avoid sending a non-full packet unless there are no currently unacked packets. Delayed ACKs delays sending ACKs to (again) minimize the number of packets sent over the network, and instead coalesce many ACKs over a prolonged period of time. When sending small messages, these interact poorly: Nagle will effectively not let you send a packet until the delayed ACK timeout expires on the other host.
The standard dictates that the delayed ACK timeout is at most 500ms, but in Linux, the actual delays are dictated by [`TCP_DELACK_MIN/MAX`](https://elixir.bootlin.com/linux/latest/ident/TCP_D …

Add option to use TCP_NODELAY (on by default)

---

Cargo.toml
build.rs
src/conn/mod.rs
src/conn/opts.rs

This PR add connect attributes support as [Perl DBD::MySQL](https://metacpan.org/pod/DBD::mysql#mysql_conn_attrs).
I confirmed that this passes a test by `cargo test connect_attrs` for MySQL 5.7.
`build.rs` was added to get `target_os` and `target_arch` cfg features as string values.
The followings is the doc comment of `Opts.connect_attrs`
---
Connect attributes
This value is sent to the server as custom name-value attributes.
You can see them from performance_schema tables: [`session_account_connect_attrs`
and `session_connect_attrs`][attr_tables] when the server is MySQL 5.6 or later,
or MariaDB 10.0 or later.
Attribute names that begin with an underscore (`_`) are not set by
application programs because they are reserved for internal use.
The following attributes are sent in addition …

Support connect attributes

---

src/conn/mod.rs

The MySQL protocol defines COM_INIT_DB / 0x02 as "change the default schema of the connection" [1]. It is used by the MySQL CLI when doing a "USE db" statement and is implemented in the c client as:
int mysql_select_db(MYSQL * mysql,
const char * db);
This pull request implements select_db(schema: &str) for mysql::Conn.
[1] https://dev.mysql.com/doc/internals/en/com-init-db.html

Add select_db(). Closes #170

---

Cargo.toml
Makefile
appveyor.yml

"flate2" uses "miniz-sys" as default (but exchangeable) backend which does not build for some targets (i686-unknown-linux-musl).
Flate2 documentation states that backends should be changed via features:
`flate2 = { version = "1.0", features = ["zlib"], default-features = false }`
The way flate2 is currently imported into mysql does not allow to change the flate2 features though. At least I don't know how that would be done.
With the PR applications can import mysql like this to enable different flate2 backends:
`mysql = { version = "*", features = ["flate2-zlib"], default-features = false }`
Mostly this change does not break the way mysql gets imported. There are two exceptions:
`mysql = { version = "*", features = ["ssl"], default-features = false }`
`mysql = { version = "*", features = …

add option to configure features of the dependency "flate2".

---

src/conn/mod.rs
src/conn/opts.rs

Connect attributes are not set to `performance_schema.session_account_connect_attrs` when the system variable `performance_schema` is off or `performance_schema_session_connect_attrs_size` is too small. So connect attribute test fails in such cases.
This pull request fixes document and makes the test fail with the following informational messages:
* The system variable `performance_schema` is off. Restart the MySQL server with `--performance_schema=on` to pass the test.
* The system variable `performance_schema_session_connect_attrs_size` is {}. Restart the MySQL server with `--performance_schema_session_connect_attrs_size=-1` to pass the test.
I firstly had changed the code to skip tests in the above cases. However connect attributes might not be tested on some environments if tests are …

Fix connect attribute test and document.

---

Cargo.toml
src/io/tcp.rs

Use `poll` to replace `select` for creating a TCP connection on *nix platform, fixed https://github.com/rust-lang/libc/issues/1401
Because `select` has  an upper limit as `FD_SETSIZE`, and if the process has many file descriptors, it will panic at
```rust
fd_set.insert(socket_fd);
```
The backtrace:
```
0:     0x55d9ba51486d - backtrace::backtrace::libunwind::trace::h5d5f7561c1a9102a
at /root/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/backtrace-0.2.3/src/backtrace/libunwind.rs:54
- backtrace::backtrace::trace::h1a0e9cf6143fd38a
at /root/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/backtrace-0.2.3/src/backtrace/mod.rs:70
1:     0x55d9ba514512 - backtrace::capture::Backtrace::new::h5f5871afa8f4b8c8
at /var/lib/docker/volumes/jenkins-slave-2/_data/workspace/ceresdb.d …
```

(feat) Use poll instead of select for tcp connections

---

src/conn/mod.rs

`Conn::get_system_var()` unwraps the `Result` from `Conn::query()`, which may be an `Err` and cause panic. This PR just returns the `Err` to caller and avoids panic.
The backtrace:
```
panicked 'called `Result::unwrap()` on an `Err` value: IoError { Resource temporarily unavailable (os error 11) }' at "src/libcore/result.rs:999"
stack backtrace:
0:     0x7fe24c3e37ed - backtrace::backtrace::libunwind::trace::hc337d5444fd0a0f5
at /root/.cargo/registry/src/gitlab.alipay-inc.com-bfbf2811318eff5d/backtrace-0.2.3/src/backtrace/libunwind.rs:54
- backtrace::backtrace::trace::ha937d415e37244c5
at /root/.cargo/registry/src/gitlab.alipay-inc.com-bfbf2811318eff5d/backtrace-0.2.3/src/backtrace/mod.rs:70
1:     0x7fe24c3e35f2 - backtrace::capture::Backtrace::new::h97acc86c3eaf11ae
at …
```

Fix get_system_var() may panic when query() returns Err

---

Cargo.toml
LICENSE-APACHE
LICENSE-MIT
README.md
README.tpl
appveyor.yml
build.rs
src/conn/local_infile.rs
src/conn/mod.rs
src/conn/opts.rs
src/conn/pool.rs
src/conn/query_result.rs
src/conn/stmt.rs
src/conn/stmt_cache.rs
src/conn/transaction.rs
src/error.rs
src/io/mod.rs
src/io/tcp.rs
src/lib.rs
src/queryable.rs

This PR:
* Changes statement to be the thin wrapper over statement id and meta;
* Changes how statement cache works;
* Extends the `Queryable` trait;
* Fixes ipv6 parsing for urls;
* Changes option builders to be "by-value";
* Extends crate-level docs.

Thin statement

---

src/conn/pool.rs

If the `.reset()` fails here, after we decrement `count` but before a `PooledConn` is constructed, then PooledConn's `drop` is never run and `count` is never re-incremented. After this has happened `max_threads` times,  `.get_conn()` will never succeed again.
Instead, if a `.reset()` fails, drop the `Conn` (so that its "incomplete connection" state is destroyed) and decrement `count` accordingly.

Fix pool exhaustion on connection failure

---

src/conn/query_result.rs
src/lib.rs

Users of the crate might want to write functions that take a generic QueryResult. They cannot do that unless they access the Protocol trait to write their own generic bounds, such as: `fn do_something<P: Protocol>(qr: QueryResult<'_, '_, '_, P>) { ... }`

Export the Protocol trait

---

README.md

Trait name Queryable contains a typo in README

Fixing Queryable typo in README.md

---

src/conn/opts.rs

Fix doc for OptsBuilder

---

src/conn/opts.rs
src/io/mod.rs

Add support for supplying root cert in `.pem` format
Right now, there is only support for `.der` format. `.pem` is another popular format, and it would be great if `mysql` crate could support it directly for root certificate without a need to converting it to `.der`, as is currently recommended.

Add support for supplying root cert in .pem format

---

src/conn/mod.rs

in default, the program_name of attr from os.env::args[0], sometimes caller want to change it.
let opts = OptsBuilder::from_opts(&url);
let mut connect_attrs = HashMap::new();
connect_attrs.insert("program_name", "my_app");
let opts = opts.connect_attrs(connect_attrs);
let pool = Pool::new(opts)?;

get program_name from attr first

---

src/conn/queryable.rs

Fix typo in src/conn/queryable.rs

---

src/conn/pool.rs

1. Reduced `Arc` usage in `Pool`. 
It seems like there is no reason to have 4 different `Arc`s for each property of `Pool`. So they were replaced by a single `Arc`.
2. Reduced atomics usage in `Pool`.
There is no reason for `min` and `max` properties of `Pool` to be an atomic type. They can't be updated since `Pool`s creation. So they were replaced by the simple `usize`.
Since every `Arc` uses two atomics, this reduces usage of atomics from 11 to just 3. It also helps to reduce CPU cache misses, since the whole struct lays at single position in memory.

Pool struct optimizations

---

src/conn/mod.rs
src/conn/opts/mod.rs
src/io/mod.rs
src/io/tcp.rs

TCP timeouts are hard.
I have observed that in one specific scenario, namely when target endpoint goes down in aws land, application connecting to db hangs for around 15 minutes, even with setting the connect_timeout, I don't want to set read_timeout as that may have undesirable effect on long executing queries
Now, my knowledge in tcp is very accidental, but the `TCP_USER_TIMEOUT` seems to achieve the desired behavior.
I have added 2 commits:
1) impl  as_raw_fd(), this way I could have modified the user_timeout without having to hack the library
2) Since I am here, add support in Opts to handle `tcp_user_timeout` via ops.
I have not tested whether this builds on non linux platform.

Expose as fd + opts can set tcp_user_timeout

---

README.md
src/conn/mod.rs
src/conn/opts/mod.rs
src/io/mod.rs
src/io/tcp.rs
src/lib.rs

Currently the library only allows setting of the keepalive idle time
I think that is driven by the fact the socket2 only exposes this code easily - that is without the `all` feature flag.
Well, it's kinda odd that they do only that, so I have raised a PR there: https://github.com/rust-lang/socket2/pull/294 but I am not sure if that will be merged and when.
In the meantime we can easily add the support of that into this crate, just by using more `roo` API.

keepalive: allow setting of probe interval & probe count

---

Cargo.toml
src/error/mod.rs

This decreases build times slightly.
nix is only used to provide a [`From` implementation](https://github.com/blackbeam/rust-mysql-simple/blob/3c4d4eeb1222c863bac82d98dc5700a9914ccb68/src/error/mod.rs#L161-L165), we don't actually need the full crate.

Upgrade nix to 0.24.1, limit features

---

src/conn/opts/mod.rs

Directly instantiating a connection from a URL no longer seems possible with version 22.1.0. Maybe there is a "better" way to do it compared to what I did here.

Fix docu for creating a connection from URL

---

src/error/mod.rs

The current `Result` alias [can cause confusing errors for users](https://users.rust-lang.org/t/conflicting-messages-when-i-try-to-provide-an-implementation-for-mysql-fromrow/90474/1) who use glob imports. This tweak makes it transparently support two-arg usage.

Use user-friendly Result alias

---

src/conn/pool/inner.rs

https://github.com/blackbeam/rust-mysql-simple/blob/e0fbfe41f23e9004a0bd7f997c388591ce07b40b/src/conn/pool/inner.rs#L70-L84
Here `count` is employed solely for counting purposes, rather than for synchronizing access to other shared variables. While Ordering::SeqCst guarantees program correctness, it can also impact performance. Therefore, using Ordering::Relaxed is sufficient to maintain the program's correctness without adversely affecting its efficiency.

Fine-tune the Ordering for count

---

src/conn/mod.rs
src/conn/pool/mod.rs

It would be nicer to use `.ping()` [in `r2d2_mysql`'s health checks for connections](https://github.com/outersky/r2d2-mysql/blob/15db0f31a2ad10f5e28f9ab86b45391269d416e1/src/pool.rs#L30-L32). As it is, we have to either run a query or use `.ping()` and lose source information.
It is easy for downstream users to call `.is_ok()` on the `Result` to get the bool back. It is not possible, however, to go the other way without losing information.
This is a breaking API change.

feat!: ping and select_db return Result

---

README.md
src/lib.rs

Fixed a few grammar mistakes in the docs.
- ~than~ then
- ~it's~ its

docs: fix typos

---

azure-pipelines.yml

With MariaDB-11.4 now GA test this with a lts tag.
Take the quay.io/mariadb-foundation/mariadb-devel images so compatibility errors can be found before MariaDB releases.
Use the healthcheck.sh script in the MariaDB container to determine if ready.
Use mariadb client in the container as newer containers will no longer have mysql.

ci: mariadb - new versions

---

Cargo.toml
src/conn/stmt_cache.rs

Thanks for using my crate!
Note that version 2.0 increases the MSRV to Rust 1.81. I understand if you don't want to upgrade right away, but hopefully this PR will be useful when you do.
I'm opening these PRs for the top users of twox-hash and have no current plans to become a consistent contributor to this specific repository; please feel free to rewrite the commit as appropriate for your project's requirements.

Upgrade to twox-hash 2.0
